### ISSUE TITLE
Trouble with setup

### ISSUE THREAD

**Issue by mcauley-penney** [NFrid/due.nvim#2]
Hey, awesome plugin! I prefer text files over org, so this is right up my alley. 

I am having trouble using due.nvim without additional configuration. After installation via packer, it is unresponsive. Where may I start debugging?

**Comment by nfrid** [comment]
Hello. Can you explain what do you mean by 'unresponsive'? The whole neovim is freezing or it's just plugin doesn't work?

You can actually go to the directory where packer clones all the plugin repos (on linux it's usually `~/.local/share/nvim/site/pack/packer/start/NAME_OF_PLUGIN_REPO`) and try to edit `lua/due_nvim.lua`.

**Comment by mcauley-penney** [comment]
I apologize, I should have provided more info! The plugin is not working for me. 

I have been looking at the code but I assumed that this version is the same used in your gif, so it should work. It is definitely something with my personal configuration, but I don't know what. I am experimenting right now to try and find why it is not responding. I asked if there was a specific place I should start debugging just in case you were aware of a case that may stop due.nvim from working properly.

Edit: I spoke too soon! I resolved the issue, it was user error
