### ISSUE TITLE
[Feature] Add time

### ISSUE THREAD

**Issue by cipherodio** [NFrid/due.nvim#5]
im using taskwarrior before, but then i found this plugin and remove taskwarrior. i like this more because it is more minimal and im using it with vimwiki and todo-comments, but one thing is missing, the feature to add time and not just date only. 
for example i just want to set a **TODO** for today at specific time. so i can just do:
```
TODO: Feed my dog <2022-03-03> <08:00 PM> due: 1hr 30mins
```

thanks for this great simple plugin 😊

**Comment by nfrid** [comment]
thank you for the sweet words
done, you can tune pattern matching a bit with new configs if you need specific format, I did <date hh:mm( am/pm)> by default
you might want to turn either use_clock_time or use_clock_today to display hours and minutes
