### ISSUE TITLE
Time issue again

### ISSUE THREAD

**Issue by cipherodio** [NFrid/due.nvim#7]
hi sir 😅 it is me again. the fix you did already fix the issue but another issue again. for example:
`(2022-03-10 12:00 AM) due: 1hr 3min 21s` but after the due of `1hr 3min 21s` the `due:` should state that it is `OVERDUE` however it reset and show `due:` for the next day of `12:00 am`

Like this on my  notes:
```
Departure (2022-03-10 12:00 AM) due: 16h 38min 26s
```

Expected result: and it should stay `OVERDUE`
```
Departure (2022-03-10 12:00 AM) due: OVERDUE
```

**Comment by nfrid** [comment]
This am/pm system is frustrating...
I hope it finally works now, thanks again

**Comment by cipherodio** [comment]
yea sorry man 😅 after the fix the time for the current date doesnt work now 😅 for example is set the due today with:
`(2022-03-10 11:00 pm)` it says `OVERDUE` already eventhough it has 2hours before the due, this is working before the last fix 😅

**Comment by nfrid** [comment]
one day I'll just start writing unit tests on all of my projects..
This is fixed now. Again. Probably...

**Comment by cipherodio** [comment]
all is fixed now, sorry if it got you frustrated 😅 thank you very much for fixing this great plugin bro. 😊
