### ISSUE TITLE
[Feature Request] Provide sorting and filtering to act as general agenda

### ISSUE THREAD

**Issue by wakatara** [NFrid/due.nvim#8]
I really like what you've done here. Would love to see it further enhanced to provide a general capability for sorting and filtering due date times in order to provide a more general agenda capability.

eg. filter in place "Overdue"
Or filter in place Due in 1d to 7d 
etc

Anyway, cool plugin. Playing with it now.

**Comment by wakatara** [comment]
In fact, imagine this kinda combined with a slightly more enhanced taskpaper.vim... =]

**Comment by nfrid** [comment]
Sorry. This plugin has only purpose - to display due dates. I see it as a part of the agenda setup, not the whole system, so you can have a plugin that adds some filtering capatibility, a plugin for displaying 'calendars', a todo-management plugin, etc.
Maybe I'll make some 'middleman' plugin for it, so different plugins could share one API.. but not in the near future :(

If you need an agenda functionality out of the box, I recommend you to try out org-mode in Emacs. Unfortunately, I haven't seen any good (neo)vim plugin as powerful as it is.

Anyway, thanks for the kind words 👽

**Comment by wakatara** [comment]
Lol... I'm actually looking to replace org-mode and emacs with somethig in vim which is why I was asking the question (and mentioned taskpaper). Fair enough though. Completely understand. 

thanks for considering the request!   (obviously, I am going ot have to teach myself some lua... ).

**Comment by wakatara** [comment]
(and, of course, thanks for all your hard work on this plugin... )

**Comment by illumiko** [comment]
@wakatara try neorg
